global:
  message: Welcome to notification service dev environment!!
server:
  port: 8086
message: Hello from Dev!
spring:
  datasource:
     url: jdbc:mysql://localhost:3306/notification
     username: root
     password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
