spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/notification
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    
