spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/payment
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    
